### ISSUE TITLE
ERROR, MMF does not exists!

### ISSUE THREAD

**Issue by nhansinh** [elecyb/OSPE#2]
Hello,
I choose any program that has this error, how to fix it?
Can you help me?
Thanks

**Comment by elecyb** [comment]
Hello,
That error happens when the Memory Mapped File was not successfully created by the injected DLL.
Probably the code that setups the hooks is outdated or not working.

If you trying to sniff a Web Browser traffic I suggest to do it with Firefox 32bit version (compiling OspeSpy.dll in x86). I tested the latest version of firefox and worked perfectly.

Regards

**Comment by nhansinh** [comment]
Hello,
I use it well on 32bit, thank you very much.
Best regards,

**Comment by hykh** [comment]
i have try 32bit too but doesn't work too please help me if you are there
